//export * from './EffectivePermissionsApi';
//import { EffectivePermissionsApi } from './EffectivePermissionsApi';
//export * from './PermissionsApi';
//import { PermissionsApi } from './PermissionsApi';
export * from './PrincipalClaimsApi';
import { PrincipalClaimsApi } from './PrincipalClaimsApi';
export * from './PrincipalRolesApi';
import { PrincipalRolesApi } from './PrincipalRolesApi';
export * from './PrincipalsApi';
import { PrincipalsApi } from './PrincipalsApi';
//export * from './RealmClaimsApi';
//import { RealmClaimsApi } from './RealmClaimsApi';
//export * from './RealmsApi';
//import { RealmsApi } from './RealmsApi';
//export * from './ResourcesApi';
//import { ResourcesApi } from './ResourcesApi';
export * from './RolesApi';
import { RolesApi } from './RolesApi';
export * from './IdmUsersApi';
import { IdmUsersApi } from './IdmUsersApi';
//export const APIS = [EffectivePermissionsApi, PermissionsApi, PrincipalClaimsApi, PrincipalRolesApi, PrincipalsApi, RealmClaimsApi, RealmsApi, ResourcesApi, RolesApi, IdmUsersApi];
